name: Ops

on:
  workflow_dispatch:
    inputs:
      task:
        description: Select task to run on self-hosted runner
        required: true
        default: build
        type: choice
        options:
          - build
          - test
          - start-check
          - e2e

jobs:
  ops:
    runs-on: self-hosted
    env:
      NODE_ENV: test
      MONGOMS_VERSION: '7.0.5'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci || npm install
      - name: Build
        if: ${{ inputs.task == 'build' || inputs.task == 'test' || inputs.task == 'e2e' }}
        run: npm run build
      - name: Test
        if: ${{ inputs.task == 'test' }}
        run: npm test
      - name: E2E (start app + run script)
        if: ${{ inputs.task == 'e2e' }}
        env:
          PORT: 3000
          MONGO_URL: ${{ env.MONGO_URL || 'mongodb://127.0.0.1:27017/rentalapp_ops' }}
          NODE_ENV: development
          ESCROW_DRIVER: mock
          JWT_SECRET: insecure
        run: |
          # Ensure MongoDB available
          if ! command -v mongod >/dev/null 2>&1; then
            echo "Installing MongoDB Community via Homebrew..."
            brew tap mongodb/brew
            brew install mongodb-community@7.0
          fi
          brew services start mongodb-community@7.0 || true
          echo "Starting app on :$PORT with MONGO_URL=$MONGO_URL"
          node dist/app.js &
          APP_PID=$!
          # wait for health
          for i in {1..30}; do
            sleep 1
            curl -fsS http://127.0.0.1:$PORT/health && break || true
          done
          echo "Health:" && curl -sS http://127.0.0.1:$PORT/health || true
          npx ts-node scripts/e2e.ts
          kill $APP_PID || true
      - name: Start + Health check
        if: ${{ inputs.task == 'start-check' }}
        env:
          PORT: 3000
          # Expect a local MongoDB; override in dispatch if needed
          MONGO_URL: ${{ env.MONGO_URL || 'mongodb://127.0.0.1:27017/rentalapp_ops' }}
          NODE_ENV: development
        run: |
          # Ensure MongoDB is available locally
          if ! command -v mongod >/dev/null 2>&1; then
            echo "Installing MongoDB Community via Homebrew..."
            brew tap mongodb/brew
            brew install mongodb-community@7.0
          fi
          echo "Starting MongoDB service (if not running)..."
          brew services start mongodb-community@7.0 || true
          sleep 3
          echo "Starting app on :$PORT with MONGO_URL=$MONGO_URL"
          npm run build
          node dist/app.js &
          APP_PID=$!
          echo "PID=$APP_PID"
          # wait a bit for server
          for i in {1..30}; do
            sleep 1
            curl -fsS http://127.0.0.1:$PORT/health && break || true
          done
          echo "Health response:" && curl -sS http://127.0.0.1:$PORT/health || true
          # Assert OK
          STATUS=$(curl -sS http://127.0.0.1:$PORT/health | jq -r '.ok' || echo "")
          if [ "$STATUS" != "true" ]; then
            echo "Health check failed" >&2
            kill $APP_PID || true
            exit 1
          fi
          kill $APP_PID || true
